### ISSUE TITLE
349にアプデしたら起動でコケる

### ISSUE THREAD

**Issue by Chipsnet** [mei23/misskey#1860]
## 💡 Summary

起動しない

## 🙂 Expected Behavior

起動する

## ☹️ Actual Behavior

エラー吐いて起動が止まる

`.npm/_logs`

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.5
3 info using node@v12.18.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle misskey@10.102.349-m544~prestart: misskey@10.102.349-m544
6 info lifecycle misskey@10.102.349-m544~start: misskey@10.102.349-m544
7 verbose lifecycle misskey@10.102.349-m544~start: unsafe-perm in lifecycle true
8 verbose lifecycle misskey@10.102.349-m544~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/misskey/misskey/node_modules/.bin:>
9 verbose lifecycle misskey@10.102.349-m544~start: CWD: /home/misskey/misskey
10 silly lifecycle misskey@10.102.349-m544~start: Args: [ '-c', 'node ./index.js' ]
11 silly lifecycle misskey@10.102.349-m544~start: Returned: code: 1  signal: null
12 info lifecycle misskey@10.102.349-m544~start: Failed to exec start script
13 verbose stack Error: misskey@10.102.349-m544 start: `node ./index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid misskey@10.102.349-m544
15 verbose cwd /home/misskey/misskey
16 verbose Linux 5.3.0-64-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.18.2
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error misskey@10.102.349-m544 start: `node ./index.js`
22 error Exit status 1
23 error Failed at the misskey@10.102.349-m544 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

## 📝 Steps to Reproduce

1. `git pull`で更新
2. `yarn install`で依存関係のインストール
3. `NODE_ENV=production yarn build`を実行してビルド
4. `sudo systemctl restart misskey`で再起動
5. 起動せずに止まる

## 📌 Environment

CPU: Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
RAM: 8GB
SSD: 216GB
OS: Lubuntu19.04

Node.js: v12.18.2
Yarn: 1.22.4

**Comment by mei23** [comment]
たぶん、肝心なログが コンソール/syslog/systemdのログ あたりに出てそうでこれだけではよくわからないけど
```
rm -rf node_moduls/sharp
yarn --force
```
あたりやればうまくいくかも

**Comment by Chipsnet** [comment]
上記で解決しました
ありがとうございました
