### ISSUE TITLE
ActivityPub公開範囲でおかしいところ

### ISSUE THREAD

**Issue by mei23** [mei23/misskey#3]
1. Misskey発の Public/Home/Follower/Directが 他インスタンス(Mastodon/Misskey問わず)にはPublicで届く
→未実装だったはず…

2. Follower宛て投稿が届かない(メンションありなし問わず)
```
Error: invalid person: object is not a person or service 'OrderedCollection'
    at validatePerson (/home/xxx/misskey/built/remote/activitypub/models/person.ts:23:10)
    at createPerson (/home/xxx/misskey/built/remote/activitypub/models/person.ts:78:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
3. DM(Direcy + メンション)がFollowerで届く
3.1. Streamingでは「この投稿は非公開です」と出てしまう

**Comment by mei23** [comment]
Public
"to":["https://www.w3.org/ns/activitystreams#Public"],
"cc":["https://SRC/users/1/followers"],

Unlisted
"to":["https://SRC/users/1/followers"],
"cc":["https://www.w3.org/ns/activitystreams#Public"],

Follower
"to":["https://SRC/users/1/followers"],
"cc":[],

Direct
"to":["https://DST/users/5b6fd9a48b2ab50cf171d001"],
"cc":[],

**Comment by mei23** [comment]
Public
"to":["https://www.w3.org/ns/activitystreams#Public"],
"cc":["https://SRC/users/1/followers"],

Unlisted
"to":["https://SRC/users/1/followers"],
"cc":["https://www.w3.org/ns/activitystreams#Public"],

Follower
"to":["https://SRC/users/1/followers"],
"cc":[],

Direct
"to":["https://DST/users/ID"],
"cc":[],

**Comment by mei23** [comment]
2, 3 はマージ済み
- pull: https://github.com/syuilo/misskey/pull/2172
  - issues: https://github.com/syuilo/misskey/issues/2170
  - issues: https://github.com/syuilo/misskey/issues/2171

3.1 はローカルだけでも起きるので別のバグ

1 は実装（修正？）しようかと

**Comment by mei23** [comment]
Announceの方にもto,cc=>公開範囲判定があるみたい
