### ISSUE TITLE
Questionの選択肢に空文字列があるとinboxキューがスタックする

### ISSUE THREAD

**Issue by mei23** [mei23/misskey#909]
## 💡 Summary
```
{
  '@context': [
    'https://www.w3.org/ns/activitystreams',
    'https://anime.website/schemas/litepub-0.1.jsonld',
    { '@language': 'und' }
  ],
  actor: 'https://anime.website/users/wowaname',
  attachment: [],
  attributedTo: 'https://anime.website/users/wowaname',
  cc: [ 'https://www.w3.org/ns/activitystreams#Public' ],
  closed: '2020-03-11T12:09:59.123759',
  content: "<span class='h-card'><a data-user='9phZ48yY3GkFR9NItk' class='u-url mention' href='https://princess.cat/users/mewmew'>@<span>mewmew</span></a></span> polls are",
  context: 'https://princess.cat/contexts/fc94201d-9048-4502-b29a-a9343ff0688d',
  conversation: 'https://princess.cat/contexts/fc94201d-9048-4502-b29a-a9343ff0688d',
  id: 'https://anime.website/objects/3c94c051-e652-4aff-bd93-b8fadb12f8dd',
  inReplyTo: 'https://princess.cat/objects/ceedaa11-518e-475b-a865-1fc047f0d040',
  oneOf: [
    {
      name: 'good',
      replies: { totalItems: 2, type: 'Collection' },
      type: 'Note'
    },
    {
      name: 'bad',
      replies: { totalItems: 1, type: 'Collection' },
      type: 'Note'
    },
    {
      name: '',
      replies: { totalItems: 5, type: 'Collection' },
      type: 'Note'
    },
    {
      name: '',
      replies: { totalItems: 5, type: 'Collection' },
      type: 'Note'
    }
  ],
  published: '2020-03-10T12:09:59.125888Z',
  sensitive: false,
  summary: '',
  tag: [
    {
      href: 'https://princess.cat/users/mewmew',
      name: '@mewmew@princess.cat',
      type: 'Mention'
    }
  ],
  to: [
    'https://princess.cat/users/mewmew',
    'https://anime.website/users/wowaname/followers'
  ],
  type: 'Question'
}
```

```
{
  '@context': [
    'https://www.w3.org/ns/activitystreams',
    'https://anime.website/schemas/litepub-0.1.jsonld',
    { '@language': 'und' }
  ],
  actor: 'https://anime.website/users/wowaname',
  attachment: [],
  attributedTo: 'https://anime.website/users/wowaname',
  cc: [ 'https://www.w3.org/ns/activitystreams#Public' ],
  closed: '2020-03-11T12:09:59.123759',
  content: "<span class='h-card'><a data-user='9phZ48yY3GkFR9NItk' class='u-url mention' href='https://princess.cat/users/mewmew'>@<span>mewmew</span></a></span> polls are",
  context: 'https://princess.cat/contexts/fc94201d-9048-4502-b29a-a9343ff0688d',
  conversation: 'https://princess.cat/contexts/fc94201d-9048-4502-b29a-a9343ff0688d',
  id: 'https://anime.website/objects/3c94c051-e652-4aff-bd93-b8fadb12f8dd',
  inReplyTo: 'https://princess.cat/objects/ceedaa11-518e-475b-a865-1fc047f0d040',
  oneOf: [
    {
      name: 'good',
      replies: { totalItems: 2, type: 'Collection' },
      type: 'Note'
    },
    {
      name: 'bad',
      replies: { totalItems: 1, type: 'Collection' },
      type: 'Note'
    },
    {
      name: '',
      replies: { totalItems: 5, type: 'Collection' },
      type: 'Note'
    },
    {
      name: '',
      replies: { totalItems: 5, type: 'Collection' },
      type: 'Note'
    }
  ],
  published: '2020-03-10T12:09:59.125888Z',
  sensitive: false,
  summary: '',
  tag: [
    {
      href: 'https://princess.cat/users/mewmew',
      name: '@mewmew@princess.cat',
      type: 'Mention'
    }
  ],
  to: [
    'https://princess.cat/users/mewmew',
    'https://anime.website/users/wowaname/followers'
  ],
  type: 'Question'
}
```

```
TypeError: Cannot read property 'node' of null
    at preorder (misskey/built/prelude/tree.js:17:15)
    at Array.map (<anonymous>)
    at Object.preorderF (misskey/built/prelude/tree.js:21:30)
    at Object.default_1 [as default] (misskey/built/misc/extract-emojis.js:7:31)
    at misskey/built/services/note/create.js:142:94
    at new Promise (<anonymous>)
    at Object.exports.default (misskey/built/services/note/create.js:72:57)
    at Object.createNote (misskey/built/remote/activitypub/models/note.js:222:34)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async fetchAny (misskey/built/server/api/endpoints/ap/show.js:108:22)
    at async misskey/built/server/api/endpoints/ap/show.js:39:20
    at async Object.exports.default (misskey/built/server/api/call.js:64:12)
```

## 📝 Steps to Reproduce

1.
2.
3.

**Comment by mei23** [comment]
https://github.com/mei23/misskey/commit/f2c1f2de504c1a8ec976103e392c5244ed740fdf
